// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: analytics_ingest.proto

package ingest

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ReportIngestServerService defines service.
type ReportIngestServerService interface {
	// SubmitEvents SubmitEvents 批量上报事件
	SubmitEvents(ctx context.Context, req *SubmitEventsReq) (*SubmitEventsRsp, error)
}

func ReportIngestServerService_SubmitEvents_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SubmitEventsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ReportIngestServerService).SubmitEvents(ctx, reqbody.(*SubmitEventsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ReportIngestServerServer_ServiceDesc descriptor for server.RegisterService.
var ReportIngestServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.report.ReportIngestServer",
	HandlerType: ((*ReportIngestServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.report.ReportIngestServer/SubmitEvents",
			Func: ReportIngestServerService_SubmitEvents_Handler,
		},
	},
}

// RegisterReportIngestServerService registers service.
func RegisterReportIngestServerService(s server.Service, svr ReportIngestServerService) {
	if err := s.Register(&ReportIngestServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ReportIngestServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedReportIngestServer struct{}

// SubmitEvents SubmitEvents 批量上报事件
func (s *UnimplementedReportIngestServer) SubmitEvents(ctx context.Context, req *SubmitEventsReq) (*SubmitEventsRsp, error) {
	return nil, errors.New("rpc SubmitEvents of service ReportIngestServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ReportIngestServerClientProxy defines service client proxy
type ReportIngestServerClientProxy interface {
	// SubmitEvents SubmitEvents 批量上报事件
	SubmitEvents(ctx context.Context, req *SubmitEventsReq, opts ...client.Option) (rsp *SubmitEventsRsp, err error)
}

type ReportIngestServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewReportIngestServerClientProxy = func(opts ...client.Option) ReportIngestServerClientProxy {
	return &ReportIngestServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ReportIngestServerClientProxyImpl) SubmitEvents(ctx context.Context, req *SubmitEventsReq, opts ...client.Option) (*SubmitEventsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.report.ReportIngestServer/SubmitEvents")
	msg.WithCalleeServiceName(ReportIngestServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ReportIngestServer")
	msg.WithCalleeMethod("SubmitEvents")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SubmitEventsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
