// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: analytics_query.proto

package query

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ReportQueryServerService defines service.
type ReportQueryServerService interface {
	// QueryEvents QueryEvents 查询通用事件
	QueryEvents(ctx context.Context, req *QueryEventsReq) (*QueryEventsRsp, error)
	// QueryProblemEnterEvents QueryProblemEnterEvents 查询进入题目事件
	QueryProblemEnterEvents(ctx context.Context, req *QueryProblemEnterEventsReq) (*QueryProblemEnterEventsRsp, error)
	// QuerySolutionSubmittedEvents QuerySolutionSubmittedEvents 查询提交事件
	QuerySolutionSubmittedEvents(ctx context.Context, req *QuerySolutionSubmittedEventsReq) (*QuerySolutionSubmittedEventsRsp, error)
}

func ReportQueryServerService_QueryEvents_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryEventsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ReportQueryServerService).QueryEvents(ctx, reqbody.(*QueryEventsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ReportQueryServerService_QueryProblemEnterEvents_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryProblemEnterEventsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ReportQueryServerService).QueryProblemEnterEvents(ctx, reqbody.(*QueryProblemEnterEventsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ReportQueryServerService_QuerySolutionSubmittedEvents_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QuerySolutionSubmittedEventsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ReportQueryServerService).QuerySolutionSubmittedEvents(ctx, reqbody.(*QuerySolutionSubmittedEventsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ReportQueryServerServer_ServiceDesc descriptor for server.RegisterService.
var ReportQueryServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.report.ReportQueryServer",
	HandlerType: ((*ReportQueryServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.report.ReportQueryServer/QueryEvents",
			Func: ReportQueryServerService_QueryEvents_Handler,
		},
		{
			Name: "/oj.report.ReportQueryServer/QueryProblemEnterEvents",
			Func: ReportQueryServerService_QueryProblemEnterEvents_Handler,
		},
		{
			Name: "/oj.report.ReportQueryServer/QuerySolutionSubmittedEvents",
			Func: ReportQueryServerService_QuerySolutionSubmittedEvents_Handler,
		},
	},
}

// RegisterReportQueryServerService registers service.
func RegisterReportQueryServerService(s server.Service, svr ReportQueryServerService) {
	if err := s.Register(&ReportQueryServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ReportQueryServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedReportQueryServer struct{}

// QueryEvents QueryEvents 查询通用事件
func (s *UnimplementedReportQueryServer) QueryEvents(ctx context.Context, req *QueryEventsReq) (*QueryEventsRsp, error) {
	return nil, errors.New("rpc QueryEvents of service ReportQueryServer is not implemented")
}

// QueryProblemEnterEvents QueryProblemEnterEvents 查询进入题目事件
func (s *UnimplementedReportQueryServer) QueryProblemEnterEvents(ctx context.Context, req *QueryProblemEnterEventsReq) (*QueryProblemEnterEventsRsp, error) {
	return nil, errors.New("rpc QueryProblemEnterEvents of service ReportQueryServer is not implemented")
}

// QuerySolutionSubmittedEvents QuerySolutionSubmittedEvents 查询提交事件
func (s *UnimplementedReportQueryServer) QuerySolutionSubmittedEvents(ctx context.Context, req *QuerySolutionSubmittedEventsReq) (*QuerySolutionSubmittedEventsRsp, error) {
	return nil, errors.New("rpc QuerySolutionSubmittedEvents of service ReportQueryServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ReportQueryServerClientProxy defines service client proxy
type ReportQueryServerClientProxy interface {
	// QueryEvents QueryEvents 查询通用事件
	QueryEvents(ctx context.Context, req *QueryEventsReq, opts ...client.Option) (rsp *QueryEventsRsp, err error)
	// QueryProblemEnterEvents QueryProblemEnterEvents 查询进入题目事件
	QueryProblemEnterEvents(ctx context.Context, req *QueryProblemEnterEventsReq, opts ...client.Option) (rsp *QueryProblemEnterEventsRsp, err error)
	// QuerySolutionSubmittedEvents QuerySolutionSubmittedEvents 查询提交事件
	QuerySolutionSubmittedEvents(ctx context.Context, req *QuerySolutionSubmittedEventsReq, opts ...client.Option) (rsp *QuerySolutionSubmittedEventsRsp, err error)
}

type ReportQueryServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewReportQueryServerClientProxy = func(opts ...client.Option) ReportQueryServerClientProxy {
	return &ReportQueryServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ReportQueryServerClientProxyImpl) QueryEvents(ctx context.Context, req *QueryEventsReq, opts ...client.Option) (*QueryEventsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.report.ReportQueryServer/QueryEvents")
	msg.WithCalleeServiceName(ReportQueryServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ReportQueryServer")
	msg.WithCalleeMethod("QueryEvents")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryEventsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ReportQueryServerClientProxyImpl) QueryProblemEnterEvents(ctx context.Context, req *QueryProblemEnterEventsReq, opts ...client.Option) (*QueryProblemEnterEventsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.report.ReportQueryServer/QueryProblemEnterEvents")
	msg.WithCalleeServiceName(ReportQueryServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ReportQueryServer")
	msg.WithCalleeMethod("QueryProblemEnterEvents")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryProblemEnterEventsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ReportQueryServerClientProxyImpl) QuerySolutionSubmittedEvents(ctx context.Context, req *QuerySolutionSubmittedEventsReq, opts ...client.Option) (*QuerySolutionSubmittedEventsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.report.ReportQueryServer/QuerySolutionSubmittedEvents")
	msg.WithCalleeServiceName(ReportQueryServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ReportQueryServer")
	msg.WithCalleeMethod("QuerySolutionSubmittedEvents")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QuerySolutionSubmittedEventsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
