// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.19.1
// source: analytics_common.proto

package common

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportEvent 是所有上报事件的公共模型，payload 保存单个事件的业务字段。
type ReportEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`            // 事件编号
	EventName     string                 `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"`        // 事件名
	EventVersion  int32                  `protobuf:"varint,3,opt,name=eventVersion,proto3" json:"eventVersion,omitempty"` // 事件结构版本
	OccurredAt    string                 `protobuf:"bytes,4,opt,name=occurredAt,proto3" json:"occurredAt,omitempty"`      // 事件发生时间
	CreatedTime   string                 `protobuf:"bytes,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`    // 服务器接收时间
	CreatedBy     int32                  `protobuf:"varint,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`       // 操作用户
	Reporter      string                 `protobuf:"bytes,7,opt,name=reporter,proto3" json:"reporter,omitempty"`          // 上报来源
	Payload       string                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`            // 事件业务字段，UTF-8 JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEvent) Reset() {
	*x = ReportEvent{}
	mi := &file_analytics_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEvent) ProtoMessage() {}

func (x *ReportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEvent.ProtoReflect.Descriptor instead.
func (*ReportEvent) Descriptor() ([]byte, []int) {
	return file_analytics_common_proto_rawDescGZIP(), []int{0}
}

func (x *ReportEvent) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *ReportEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ReportEvent) GetEventVersion() int32 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *ReportEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *ReportEvent) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *ReportEvent) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *ReportEvent) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *ReportEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// EventReject 表示单个事件被拒绝。
type EventReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`     // 事件编号
	EventName     string                 `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"` // 事件名
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`       // 拒绝原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReject) Reset() {
	*x = EventReject{}
	mi := &file_analytics_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReject) ProtoMessage() {}

func (x *EventReject) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReject.ProtoReflect.Descriptor instead.
func (*EventReject) Descriptor() ([]byte, []int) {
	return file_analytics_common_proto_rawDescGZIP(), []int{1}
}

func (x *EventReject) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *EventReject) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventReject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// EventPayloadFilter 用于通用事件的 payload 查询条件。
type EventPayloadFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`          // payload 字段名
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`    // 字段值列表
	Exclude       bool                   `protobuf:"varint,3,opt,name=exclude,proto3" json:"exclude,omitempty"` // 是否排除匹配值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPayloadFilter) Reset() {
	*x = EventPayloadFilter{}
	mi := &file_analytics_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPayloadFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPayloadFilter) ProtoMessage() {}

func (x *EventPayloadFilter) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPayloadFilter.ProtoReflect.Descriptor instead.
func (*EventPayloadFilter) Descriptor() ([]byte, []int) {
	return file_analytics_common_proto_rawDescGZIP(), []int{2}
}

func (x *EventPayloadFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EventPayloadFilter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *EventPayloadFilter) GetExclude() bool {
	if x != nil {
		return x.Exclude
	}
	return false
}

// EventRecord 是通用事件查询结果。
type EventRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`            // 事件编号
	EventName     string                 `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"`        // 事件名
	EventVersion  int32                  `protobuf:"varint,3,opt,name=eventVersion,proto3" json:"eventVersion,omitempty"` // 事件结构版本
	OccurredAt    string                 `protobuf:"bytes,4,opt,name=occurredAt,proto3" json:"occurredAt,omitempty"`      // 事件发生时间
	CreatedTime   string                 `protobuf:"bytes,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`    // 服务器接收时间
	CreatedBy     int32                  `protobuf:"varint,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`       // 操作用户
	Reporter      string                 `protobuf:"bytes,7,opt,name=reporter,proto3" json:"reporter,omitempty"`          // 上报来源
	Payload       string                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`            // 事件业务字段，UTF-8 JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRecord) Reset() {
	*x = EventRecord{}
	mi := &file_analytics_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRecord) ProtoMessage() {}

func (x *EventRecord) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRecord.ProtoReflect.Descriptor instead.
func (*EventRecord) Descriptor() ([]byte, []int) {
	return file_analytics_common_proto_rawDescGZIP(), []int{3}
}

func (x *EventRecord) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *EventRecord) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventRecord) GetEventVersion() int32 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *EventRecord) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *EventRecord) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *EventRecord) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *EventRecord) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *EventRecord) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_analytics_common_proto protoreflect.FileDescriptor

var file_analytics_common_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6f, 0x6a, 0x2e, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0xff, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5d, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x22, 0xff,
	0x01, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x63,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x73, 0x75, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_analytics_common_proto_rawDescOnce sync.Once
	file_analytics_common_proto_rawDescData = file_analytics_common_proto_rawDesc
)

func file_analytics_common_proto_rawDescGZIP() []byte {
	file_analytics_common_proto_rawDescOnce.Do(func() {
		file_analytics_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_analytics_common_proto_rawDescData)
	})
	return file_analytics_common_proto_rawDescData
}

var file_analytics_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_analytics_common_proto_goTypes = []any{
	(*ReportEvent)(nil),        // 0: oj.report.ReportEvent
	(*EventReject)(nil),        // 1: oj.report.EventReject
	(*EventPayloadFilter)(nil), // 2: oj.report.EventPayloadFilter
	(*EventRecord)(nil),        // 3: oj.report.EventRecord
}
var file_analytics_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_common_proto_init() }
func file_analytics_common_proto_init() {
	if File_analytics_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_analytics_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analytics_common_proto_goTypes,
		DependencyIndexes: file_analytics_common_proto_depIdxs,
		MessageInfos:      file_analytics_common_proto_msgTypes,
	}.Build()
	File_analytics_common_proto = out.File
	file_analytics_common_proto_rawDesc = nil
	file_analytics_common_proto_goTypes = nil
	file_analytics_common_proto_depIdxs = nil
}
